<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/06/07 17:23:36
$this->security = array (
  'help' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'user',
      ),
    ),
  ),
);
