<?php
// auto-generated by sfCacheConfigHandler
// date: 2016/06/07 17:23:43
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

