<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/06/06 05:55:20
sfConfig::add(array(
  'app_sfCacheTagging_model_tag_name_separator' => ':',
  'app_sfCacheTagging_microtime_precision' => 5,
  'app_sfCacheTagging_object_class_tag_name_provider' => array (
),
  'app_facebook_appId' => NULL,
  'app_facebook_secret' => NULL,
  'app_facebook_domain' => NULL,
  'app_facebook_form_hash' => '# INSERT RANDOM SECRET HERE #',
  'app_hashes_petition_signing' => '# INSERT RANDOM SECRET HERE       #',
  'app_hashes_petition_text' => '# INSERT RANDOM OTHER SECRET HERE #',
  'app_hashes_widget' => '# INSERT RANDOM OTHER SECRET HERE #',
  'app_frontend_csrf_secret' => '# INSERT RANDOM OTHER SECRET HERE #',
  'app_recaptcha_secret' => NULL,
  'app_recaptcha_public' => NULL,
  'app_web_url' => 'http://INSERT.HERE/',
  'app_spf_cmd' => 'spfquery',
  'app_spf_ip' => NULL,
  'app_sf_guard_plugin_signin_form' => 'myLoginForm',
));
