<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/06/06 05:57:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=192.168.99.1;dbname=policat-master',
  'username' => 'root',
  'password' => 'tomorrowvictory67.',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_general_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
